// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1761830558);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1761836689);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1761830558);
user_pref("app.update.lastUpdateTime.region-update-timer", 1761830558);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1761830558);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1761830558);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1761830587);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1761830558);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{633aa8e2-2d7e-46f6-8bcf-ca132c8e883d}");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.downloads-button.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1761830527);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f4d9b7c9-a604-411c-80d0-58063fa40316}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1761830530);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1761830550009");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1761832326009");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1761830534931");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1761852134931");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1761830532");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230522134052");
user_pref("browser.startup.homepage_override.mstone", "113.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1761830530);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1761830532423");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "113.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CA");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "bfbf9a437e54474eae1db3687a013c03");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1761830558);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230522134052");
user_pref("extensions.lastAppVersion", "113.0.2");
user_pref("extensions.lastPlatformVersion", "113.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{6026eb1f-0981-4326-a68d-a990b3754926}\",\"addons\":{\"addons-restricted-domains@mozilla.com\":{\"version\":\"1.0.0buildid20230525.154501\"}}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a2209e9e-c56d-4e6c-8f3e-09693121313f\",\"pictureinpicture@mozilla.org\":\"6684c6b3-6eb4-4294-a829-b7c11e6c9038\",\"screenshots@mozilla.org\":\"fd8321d9-f7dc-411f-a9d0-852ebe89f87e\",\"webcompat-reporter@mozilla.org\":\"336db941-aef1-484c-82f2-8a0fa9a27a14\",\"webcompat@mozilla.org\":\"eba31fa3-57ed-4caa-9ff4-4c7388fcf1fc\",\"default-theme@mozilla.org\":\"3c89fe28-ca9c-41b8-9692-0a55833f8c92\",\"addons-search-detection@mozilla.com\":\"a6ca3f6a-a381-4096-b9f1-21a27554b132\",\"google@search.mozilla.org\":\"a38f2290-6e29-464a-8d8b-31fafc2fb157\",\"wikipedia@search.mozilla.org\":\"20c7aa43-a3e2-49ed-88ac-0fc7664fde58\",\"bing@search.mozilla.org\":\"39c2c8dc-5b72-4aba-a35f-633cc6fd12af\",\"amazon@search.mozilla.org\":\"5df20cff-5644-469d-b732-b771eb04a2f6\",\"ddg@search.mozilla.org\":\"8e85d54e-4952-465a-90f9-ffb7191163d3\",\"ebay@search.mozilla.org\":\"8573855f-db50-458d-a195-6d8a94a3d2a7\",\"addons-restricted-domains@mozilla.com\":\"a6e88eeb-e03a-4743-a50f-8252e56392fb\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1761836688);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "94531e267314de661b2205c606283fb066d781e5c11027578f2a3c3aa353437c2289544074a28101b6b6f0179f0fe6bd890a0ae2bb6e1cf9053650472576366c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1761830558);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1761830558);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1761830559);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20230522134052");
user_pref("media.gmp-manager.lastCheck", 1761830817);
user_pref("media.gmp-manager.lastEmptyCheck", 1761830817);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1761836689);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1761836688827");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "af6f1aae-742f-4084-8c86-0fbf7ddb147d");
user_pref("services.settings.clock_skew_seconds", -258);
user_pref("services.settings.last_update_seconds", 1761837370);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1761837370);
user_pref("services.settings.main.devtools-devices.last_check", 1761837370);
user_pref("services.settings.main.hijack-blocklists.last_check", 1761837370);
user_pref("services.settings.main.language-dictionaries.last_check", 1761837370);
user_pref("services.settings.main.password-recipes.last_check", 1761837370);
user_pref("services.settings.main.sites-classification.last_check", 1761837370);
user_pref("services.sync.engine.addresses.available", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1761836688);
user_pref("toolkit.startup.last_success", 1761830523);
user_pref("toolkit.telemetry.cachedClientID", "3c11c8ba-3b77-49df-9263-b285dbd76883");
user_pref("toolkit.telemetry.previousBuildID", "20230522134052");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
